### ISSUE TITLE
Planned migration of abb_driver to its own repository

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb#179]
As a consequence of the consensus reached in ros-industrial/ros_industrial_issues#49, I've extracted `abb_driver` out of this repository and have created a new repository that hosts just the driver. You may find the candidate at [ros-industrial/abb_driver](https://github.com/ros-industrial/abb_driver).

**NOTE**: this is not the final version. Things may still change.

I've tried to retain as much of the commit history as possible (and where it made sense), and will transfer any open issues as well.

Commits and file provenance have been retained, and references to issues and PRs have been updated wherever possible. Only the `kinetic-devel` branch will be created -- others can still be found here, in `ros-industrial/abb`. Of course all commits are part of the new repository, we'll just not recreate all the labels.

To give current users sufficient time to update their remotes and/or not disturb running processes, `abb_driver` will be removed from `ros-industrial/abb` in two weeks (ie: on `2020-04-19`).

Further tasks to complete the migration:

 - [x] announce the planned migration on ROS Discourse ([Migration of abb_driver to a separate repository](https://discourse.ros.org/t/migration-of-abb-driver-to-a-separate-repository/13522))
 - [x] create a new release repository ([ros-industrial-release/abb_driver-release](https://github.com/ros-industrial-release/abb_driver-release))
 - [x] update `rosdistro` entries for `abb_driver` `devel` and `doc` jobs (https://github.com/ros/rosdistro/pull/24535 and https://github.com/ros/rosdistro/pull/24536)
 - [x] release `abb_driver` again into Kinetic and Melodic
    - [x] Kinetic: ros/rosdistro#25544
    - [x] Melodic: ros/rosdistro#25545
 - ~~[ ] create a `.rosinstall` file (which includes `ros-industrial/abb` and `ros-industrial/abb_driver`) to facilitate source builds~~
 - ~~[ ] update the Travis configuration here to include `ros-industrial/abb_driver`~~
 - [x] update the readme in this repository (#181)
 - [x] remove `abb_driver` from this repository (#180)

**Comment by gavanderhoorn** [comment]
Not going to create a `.rosinstall` file, as it should not be needed: as soon as `abb_driver` has been released again, `rosdep` should be able to resolve it and it should be installed automatically.

As `abb_driver` is not needed for a from-source build of `ros-industrial/abb` (it's only an `exec_depend`), this would seem to remove the need to facilitate source builds with a `.rosinstall` file.

With the same rationale, we're not going to update the Travis configuration (as that's essentially a from-source build but then as part of CI).

**Comment by gavanderhoorn** [comment]
`abb_driver` has been removed (#180), readme updated (#181).

Only thing remaining is to release it again from the new repository.

Until that time, `abb_driver` will be built from the already released source tarball, so nothing will break, even without releasing it from the new location.

We'll keep this issue open until `abb_driver` has been released from it's new location.

**Comment by gavanderhoorn** [comment]
`abb_driver` released into Kinetic and Melodic (see OP for links to `rosdistro` PRs).

I'll close this once those PRs have been merged.

**Comment by gavanderhoorn** [comment]
Both PRs have been merged.

Pending an issue with the buildfarm ([this one](https://discourse.ros.org/t/build-ci-failures-with-ros-testing-repository-enabled/15006)), `abb_driver` will be built from its new location and be available similar to how it was available when it was still part of `ros-industrial/abb`.

As this completes the migration, I'm closing this issue.
